### ISSUE TITLE
moveit package

### ISSUE THREAD

**Issue by sayyidabeegam** [Interbotix/interbotix_ros_arms#34]
How can I edit the moveit package, for adding more poses?
When I try  with moveit setup assistant, to edit existing moveit package, that is not able to do that.

**Comment by swiz23** [comment]
Yeah, using the MoveIt setup assistant won't work since I've altered the structure and naming of the files a bit. To add more poses, you should edit the SRDF file directly. For example, to add another pose for the WX200 robot arm, look at the the Home, Sleep, and Upright poses at https://github.com/Interbotix/interbotix_ros_arms/blob/cb9f5feb6c51190561e05896ba39cd1cce133875/interbotix_moveit/config/srdf/wx200.srdf.xacro#L33, and add another pose in a similar fashion.

**Comment by sayyidabeegam** [comment]
Thank you
